version: "3"
services:
  dash_api:
    build: .
    ports:
     - "5000:5000"
    networks:
     - development-network
    volumes:
     - /tmp/dash_api:/usr/src/app/reports
    depends_on:
     - mongo

  mongo:
    image: mongo:4.0.0
    networks:
     - development-network
    volumes:
     - /var/docker/data/mongodb:/data/db
    logging:
      driver: "none"
    command: mongod --port 27017

networks:
    development-network:
        driver: bridge
